name: NodeJS CI with Electron

on:
  push:
    branches:
      - '*'
      - 'bugfix/**'
      - 'update/**'
      - 'feature/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build & Publish
        run: yarn build -- -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
